
site_name: PROPAGATOR Sim
site_description: "PROPAGATOR: An Operational Cellular-Automata Based Wildfire Simulator"
site_url: ""

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - content.code.copy
    - toc.follow

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI Usage: cli.md
  - API Reference: reference/index.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # If you use the "src/" layout, point mkdocstrings at it:
          paths: ["src"]
          # Helpful defaults:
          options:
            docstring_style: google
            show_source: true
            inherited_members: true
            merge_init_into_package: true